greeting: "안녕하세요"

spring:
    profile: dev

devguide: 
    greeting: "개발 서버에 오신걸 환영합니다."

spring:
    profile: stg

devguide: 
    greeting: "스테이징 서버에 오신걸 환영합니다."

spring:
    profile: local

devguide: 
    greeting: "상품 서버에 오신걸 환영합니다."
